console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
enable_cursor_positioning = true
auto_update = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'white'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .WSL }}wsl at {{ end }}{{.Icon}} '
    foreground = 'black'
    background = 'white'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'full'
      windows = '󰨡'
      arch = ''       
  [[blocks.segments]]
    style = 'powerline'
    template = ' {{ .Path }} '
    powerline_symbol = ''  
    foreground = 'black'
    background = 'blue'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}▼{{ end }}{{ if gt .Ahead 0 }}▲{{ end }}'
    foreground = 'black'
    background = 'cyan'
    type = 'git'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}white{{end}}']
