[packages]
[packages.arch]
[packages.arch.cli]
pacman = [
  # Container and orchestration
  "kubectl",
  "minikube",
]

aur = []

[packages.arch.desktop]
pacman = [
  # Security
  "keepassxc",

  # System utilities
  "tlp",
  "ghostty",
]

aur = [
  # Browsers
  "brave-bin",

  # Development
  "visual-studio-code-bin",
]
