[packages]
[packages.arch]
[packages.arch.cli]
pacman = [
  "kubectl",
  "minikube",
]

aur = []

[packages.arch.desktop]
pacman = [
  "tlp",
  "keepassxc",
  "ghostty",
  "discord",
]

aur = [
  "brave-bin",
  "visual-studio-code-bin",
  "youtube-music-bin",
]
