[packages]
  [packages.arch]
    pacman = [
      # Development tools
      "git",
      "base-devel",
      
      # Editors
      "vim",
      "helix",
      
      # Modern CLI tools
      "bat",
      "eza",
      "zoxide",
      "ripgrep",
      "fzf",
      "lazygit",
      
      # System utilities
      "btop",
      "tlp",
      "tlp-rdw",
      "fastfetch",
      "ghostty",
      
      # Container and orchestration
      "kubectl",
      "minikube",
      "docker-buildx",
      "docker-compose",
      
      # Security
      "keepassxc",
      
      # Creative tools
      "blender",
      "freecad"
    ]
    
    aur = [
      # Browsers
      "brave-bin",
      
      # Development
      "visual-studio-code-bin",
      "docker-rootless-extras"
    ]
